// examples/vue-sample/src/App.vue
<template>
  <header class="nhsuk-header" role="banner">
    <div class="nhsuk-width-container nhsuk-header__container">
      <div class="nhsuk-header__transactional-service-name">
        <a
          class="nhsuk-header__transactional-service-name--link"
          href="/"
          aria-label="Demo homepage"
          >Demo</a
        >
      </div>
    </div>
  </header>
  <div class="nhsuk-width-container">
    <main class="nhsuk-main-wrapper" role="main">
      <h1>NHS Number validator</h1>
      <p class="nhsuk-lede-text">
        This page is demo of the
        <a href="https://github.com/rowellx68/valid-nhsnum">valid-nhsnum</a>
        library which allows you to validate if the NHS number provided is
        valid.
      </p>

      <Validation></Validation>

      <hr class="nhsd-a-horizontal-rule">

      <Generation></Generation>
    </main>
  </div>
  <footer role="contentinfo">
    <div class="nhsuk-footer">
      <div class="nhsuk-width-container"></div>
    </div>
  </footer>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import Validation from './components/Validation.vue'
import Generation from './components/Generation.vue'

export default defineComponent({
  name: 'App',
  components: {
    Validation,
    Generation,
  },
})
</script>

// examples/with-react/src/App.tsx
import React from 'react';
import {
  Container,
  Footer,
  Header,
  Heading,
  Link,
  Main,
  Paragraph,
  ReadingWidth,
} from 'nhsuk-frontend-react';
import { ValidationSection } from './ValidationSection';
import { GenerateSection } from './GenerateSection';

export const App = () => {
  return (
    <>
      <Header serviceName="Valid NHS Number">
        <Header.Container>
          <Header.Logo
            href="https://github.com/rowellx68/valid-nhsnum"
            aria-label="Go to the NHS number validator GitHub repository"
          />
        </Header.Container>
      </Header>

      <Container>
        <Main>
          <Heading>NHS Number validator</Heading>
          <ReadingWidth>
            <Paragraph variant="lead">
              This page is demo of the{' '}
              <Link href="https://github.com/rowellx68/valid-nhsnum">
                valid-nhsnum
              </Link>{' '}
              library which allows you to validate if the NHS number provided is
              valid.
            </Paragraph>
          </ReadingWidth>

          <ValidationSection />

          <hr />

          <GenerateSection />
        </Main>
      </Container>
      <Footer />
    </>
  );
};
